INSERT INTO Car_Parking_Address(ADDRESS_ID,STREET_NAME,CITY,ZIP_CODE) VALUES(1001,'Liberty St','Schamuburg',60173);
INSERT INTO Car_Parking_Address(ADDRESS_ID,STREET_NAME,CITY,ZIP_CODE) VALUES(1002,'Kensington Cr','Wheaton',60090);
INSERT INTO Car_Parking_Address(ADDRESS_ID,STREET_NAME,CITY,ZIP_CODE) VALUES(1003,'E Rand Road','Arlington Heights',60174);
INSERT INTO Car_Parking_Address(ADDRESS_ID,STREET_NAME,CITY,ZIP_CODE) VALUES(1004,'Henderson Road','Columbus',43220);
INSERT INTO Car_Parking_Address(ADDRESS_ID,STREET_NAME,CITY,ZIP_CODE) VALUES(1005,'E Algonquin Road','Dublin',43235);

------	Parking Lot Types would be S (Smaller), M (Medium), L (Large) ------------
INSERT INTO Car_Parking_Lot(CAR_PARKING_LOT_ID,ADDRESS_ID,CAR_PARKING_LOT,CAR_PARKING_LOT_TYPE,AVALIABLE_STATUS) VALUES(2001,1001,'L11','S','Y');
INSERT INTO Car_Parking_Lot(CAR_PARKING_LOT_ID,ADDRESS_ID,CAR_PARKING_LOT,CAR_PARKING_LOT_TYPE,AVALIABLE_STATUS) VALUES(2002,1001,'L12','M','N');
INSERT INTO Car_Parking_Lot(CAR_PARKING_LOT_ID,ADDRESS_ID,CAR_PARKING_LOT,CAR_PARKING_LOT_TYPE,AVALIABLE_STATUS) VALUES(2003,1001,'L13','L','Y');
INSERT INTO Car_Parking_Lot(CAR_PARKING_LOT_ID,ADDRESS_ID,CAR_PARKING_LOT,CAR_PARKING_LOT_TYPE,AVALIABLE_STATUS) VALUES(2004,1001,'L14','S','N');
INSERT INTO Car_Parking_Lot(CAR_PARKING_LOT_ID,ADDRESS_ID,CAR_PARKING_LOT,CAR_PARKING_LOT_TYPE,AVALIABLE_STATUS) VALUES(2005,1001,'L15','L','Y');
INSERT INTO Car_Parking_Lot(CAR_PARKING_LOT_ID,ADDRESS_ID,CAR_PARKING_LOT,CAR_PARKING_LOT_TYPE,AVALIABLE_STATUS) VALUES(2006,1001,'L16','S','Y');


INSERT INTO Car_Parking_Lot(CAR_PARKING_LOT_ID,ADDRESS_ID,CAR_PARKING_LOT,CAR_PARKING_LOT_TYPE,AVALIABLE_STATUS) VALUES(2007,1002,'L21','M','Y');
INSERT INTO Car_Parking_Lot(CAR_PARKING_LOT_ID,ADDRESS_ID,CAR_PARKING_LOT,CAR_PARKING_LOT_TYPE,AVALIABLE_STATUS) VALUES(2008,1002,'L22','S','Y');
INSERT INTO Car_Parking_Lot(CAR_PARKING_LOT_ID,ADDRESS_ID,CAR_PARKING_LOT,CAR_PARKING_LOT_TYPE,AVALIABLE_STATUS) VALUES(2009,1002,'L23','M','N');
INSERT INTO Car_Parking_Lot(CAR_PARKING_LOT_ID,ADDRESS_ID,CAR_PARKING_LOT,CAR_PARKING_LOT_TYPE,AVALIABLE_STATUS) VALUES(2010,1002,'L24','L','Y');
INSERT INTO Car_Parking_Lot(CAR_PARKING_LOT_ID,ADDRESS_ID,CAR_PARKING_LOT,CAR_PARKING_LOT_TYPE,AVALIABLE_STATUS) VALUES(2011,1002,'L25','M','Y');
INSERT INTO Car_Parking_Lot(CAR_PARKING_LOT_ID,ADDRESS_ID,CAR_PARKING_LOT,CAR_PARKING_LOT_TYPE,AVALIABLE_STATUS) VALUES(2012,1002,'L26','M','N');

INSERT INTO Car_Parking_Lot(CAR_PARKING_LOT_ID,ADDRESS_ID,CAR_PARKING_LOT,CAR_PARKING_LOT_TYPE,AVALIABLE_STATUS) VALUES(2013,1003,'L31','S','Y');
INSERT INTO Car_Parking_Lot(CAR_PARKING_LOT_ID,ADDRESS_ID,CAR_PARKING_LOT,CAR_PARKING_LOT_TYPE,AVALIABLE_STATUS) VALUES(2014,1003,'L32','S','N');
INSERT INTO Car_Parking_Lot(CAR_PARKING_LOT_ID,ADDRESS_ID,CAR_PARKING_LOT,CAR_PARKING_LOT_TYPE,AVALIABLE_STATUS) VALUES(2015,1003,'L33','M','Y');
INSERT INTO Car_Parking_Lot(CAR_PARKING_LOT_ID,ADDRESS_ID,CAR_PARKING_LOT,CAR_PARKING_LOT_TYPE,AVALIABLE_STATUS) VALUES(2016,1003,'L34','L','N');
INSERT INTO Car_Parking_Lot(CAR_PARKING_LOT_ID,ADDRESS_ID,CAR_PARKING_LOT,CAR_PARKING_LOT_TYPE,AVALIABLE_STATUS) VALUES(2017,1003,'L35','S','Y');
INSERT INTO Car_Parking_Lot(CAR_PARKING_LOT_ID,ADDRESS_ID,CAR_PARKING_LOT,CAR_PARKING_LOT_TYPE,AVALIABLE_STATUS) VALUES(2018,1003,'L36','S','Y');

INSERT INTO Car_Parking_Lot(CAR_PARKING_LOT_ID,ADDRESS_ID,CAR_PARKING_LOT,CAR_PARKING_LOT_TYPE,AVALIABLE_STATUS) VALUES(2019,1004,'L41','M','N');
INSERT INTO Car_Parking_Lot(CAR_PARKING_LOT_ID,ADDRESS_ID,CAR_PARKING_LOT,CAR_PARKING_LOT_TYPE,AVALIABLE_STATUS) VALUES(2020,1004,'L42','L','Y');
INSERT INTO Car_Parking_Lot(CAR_PARKING_LOT_ID,ADDRESS_ID,CAR_PARKING_LOT,CAR_PARKING_LOT_TYPE,AVALIABLE_STATUS) VALUES(2021,1004,'L43','M','N');
INSERT INTO Car_Parking_Lot(CAR_PARKING_LOT_ID,ADDRESS_ID,CAR_PARKING_LOT,CAR_PARKING_LOT_TYPE,AVALIABLE_STATUS) VALUES(2022,1004,'L44','M','Y');
INSERT INTO Car_Parking_Lot(CAR_PARKING_LOT_ID,ADDRESS_ID,CAR_PARKING_LOT,CAR_PARKING_LOT_TYPE,AVALIABLE_STATUS) VALUES(2023,1004,'L45','S','Y');
INSERT INTO Car_Parking_Lot(CAR_PARKING_LOT_ID,ADDRESS_ID,CAR_PARKING_LOT,CAR_PARKING_LOT_TYPE,AVALIABLE_STATUS) VALUES(2024,1004,'L46','L','Y');

INSERT INTO Car_Parking_Lot(CAR_PARKING_LOT_ID,ADDRESS_ID,CAR_PARKING_LOT,CAR_PARKING_LOT_TYPE,AVALIABLE_STATUS) VALUES(2025,1005,'L51','L','N');
INSERT INTO Car_Parking_Lot(CAR_PARKING_LOT_ID,ADDRESS_ID,CAR_PARKING_LOT,CAR_PARKING_LOT_TYPE,AVALIABLE_STATUS) VALUES(2026,1005,'L52','M','N');
INSERT INTO Car_Parking_Lot(CAR_PARKING_LOT_ID,ADDRESS_ID,CAR_PARKING_LOT,CAR_PARKING_LOT_TYPE,AVALIABLE_STATUS) VALUES(2027,1005,'L53','M','Y');
INSERT INTO Car_Parking_Lot(CAR_PARKING_LOT_ID,ADDRESS_ID,CAR_PARKING_LOT,CAR_PARKING_LOT_TYPE,AVALIABLE_STATUS) VALUES(2028,1005,'L54','S','N');
INSERT INTO Car_Parking_Lot(CAR_PARKING_LOT_ID,ADDRESS_ID,CAR_PARKING_LOT,CAR_PARKING_LOT_TYPE,AVALIABLE_STATUS) VALUES(2029,1005,'L55','S','Y');
INSERT INTO Car_Parking_Lot(CAR_PARKING_LOT_ID,ADDRESS_ID,CAR_PARKING_LOT,CAR_PARKING_LOT_TYPE,AVALIABLE_STATUS) VALUES(2030,1005,'L56','L','Y');

